platform :ios,"7.0"

target 'QBProject' do
pod 'ReactiveCocoa'
pod 'SDWebImage'
pod 'Masonry'
pod 'YYModel'
pod 'AFNetworking'
pod 'FDFullscreenPopGesture', '~> 1.1'
pod 'Bugtags'
pod 'APParallaxHeader'
end
